#!/usr/bin/env zsh
# I am using zsh instead of bash.  I was having some troubles using bash with
# arrays.  Didn't want to investigate, so I just did zsh

# Remove user config for vapour to be able to stow it
rm -rf ~/.config/nvim/lua/vapour/user-config/init.lua

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done
popd

mkdir ~/.fonts
cd ~/.fonts
fc-cache -fv
